device: cuda
exp_num: 1
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/vf_fm/exps/EqM-E-test"
th_seed: 786
np_seed: 786

unet:
  dim: [3, 128, 128]
  out_channels: 3
  channel_mult: "1, 1, 2, 3, 4"
  num_channels: 64
  res_blocks: 2
  head_chans: 64
  attn_res: "32, 16, 8"
  dropout: 0.0
  new_attn: True
  film: True
  class_cond: False
  num_classes: null

FM:
  sched: "trunc_decay"
  lamda : 4.
  return_noise : False

dataloader:
  datapath: [['/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/multi_fidelity/synthetic/turb/turb_128_.npy']]
  batch_size: 10
  dataset: Joint
  contrastive : False

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

train_eps: False
num_epochs: 100
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
restart: False
restart_epoch: